changelog:
  exclude:
    labels:
      - skip-changelog
      - documentation
      - ci
    authors:
      - dependabot
      - pre-commit-ci
  categories:
    - title: Added
      labels:
        - enhancement
    - title: Changed
      labels:
        - BREAKING
    - title: Fixed
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
