repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.286
  hooks:
  - id: ruff
    args: [ --fix, --exit-non-zero-on-fix ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-json
    types: ["jupyter"]
  - id: check-yaml
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer

# Basic notebook checks, to be run on all notebooks

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    - id: nbqa-ruff
      files: ^notebooks/
      # Ignore SHAP Paper, as it is a record of a paper rather than maintained docs
      # Ignore "Simple Boston Demo.ipynb" for now until it is properly written
      exclude: 'tree_shap_paper|Boston.Demo'
      args: [
        "--select=F",
        "--ignore=F401",  # imported but unused
        "--ignore=F403",  # import *
        "--ignore=F404",  # `from __future__` imports must occur at the beginning
        "--ignore=F405",  # variable may be undefined
        "--ignore=F841",  # variable assigned to but never used
      ]

# More stringent notebook linting checks, enabled on a subset of notebooks
# Add a notebook to the "cleanNotebooks" list below once it has been cleaned up
# See: https://github.com/shap/shap/issues/3036

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black-jupyter
    files: &cleanNotebooks |
            (?x)^(
                notebooks/api_examples/explainers/Exact.ipynb|
                notebooks/api_examples/maskers/custom.ipynb|
            )$
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    - id: nbqa-ruff
      files: *cleanNotebooks
