repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.286
  hooks:
  - id: ruff
    args: [ --fix, --exit-non-zero-on-fix ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-json
    types: ["jupyter"]
  - id: check-yaml
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer

# Hooks just for ReadTheDocs notebooks

# Black to be enabled in future
# - repo: https://github.com/psf/black
#   rev: 23.7.0
#   hooks:
#   - id: black-jupyter
#     files: ^notebooks/
#     types: [jupyter]

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    - id: nbqa-ruff
      files: ^notebooks/
