repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.286
  hooks:
  - id: ruff
    # Note: When using pre-commit, ruff's "include" and "exclude" config is ignored.
    args: [ --fix, --exit-non-zero-on-fix ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-json
    types: ["jupyter"]
  - id: check-yaml
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer

# More stringent notebook linting checks, enabled only on a subset of notebooks.
# Add a notebook to the "cleanNotebooks" list below once it has been cleaned up
# See: https://github.com/shap/shap/issues/3036

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black-jupyter
    name: black (fixed notebooks)
    files: &cleanNotebooks |
            (?x)^(
                notebooks/api_examples/explainers/Exact.ipynb|
                notebooks/api_examples/maskers/custom.ipynb|
            )$
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.286
  hooks:
  - id: ruff
    name: ruff (fixed notebooks)
    types_or: [jupyter]
    files: *cleanNotebooks
