[build-system]
requires = ["setuptools", "wheel", "oldest-supported-numpy", "packaging>20.9"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--mpl"
testpaths = ["tests"]

[tool.ruff]
select = [
  "F",  # pyflakes
  "I",  # isort
  "UP",  # pyupgrade
]
target-version = "py37"

[tool.ruff.per-file-ignores]
# Unused imports often intentional in top-level __init__.py
"__init__.py" = ["F401"]
# Don't apply linting/formatting to vendored code
"shap/explainers/other/_maple.py" = ["ALL"]
"shap/plots/colors/_colorconv.py" = ["ALL"]

[tool.cibuildwheel]
skip = ["cp36-*", "pp*", "*-musllinux_*", "*-manylinux_i686", "*_ppc64le", "*_s390x"]
build-verbosity = 2
test-command = "pytest -v {project}/tests"
test-extras = ["test", "plots"]
# skipping cp37 since catboost wheel not available
# skipping cp38-macosx_x86_64 because of https://github.com/catboost/catboost/issues/2371
test-skip = "cp37-* cp38-macosx_x86_64"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.linux]
archs = ["auto", "aarch64"]
