[build-system]
requires = ["setuptools", "wheel", "oldest-supported-numpy", "packaging>20.9"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--mpl"
testpaths = ["tests"]

[tool.ruff]
select = ["F"]
ignore = [
]

[tool.ruff.per-file-ignores]
# Unused imports often intentional in top-level __init__.py 
"__init__.py" = ["F401"]
# Don't apply linting/formatting to vendored code
"shap/explainers/other/_maple.py" = ["ALL"]
"shap/plots/colors/_colorconv.py" = ["ALL"]
