name: Feature Request
description: Suggest an idea for shap
title: "ENH: "
labels: [enhancement]

body:
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve, e.g. "I wish I could use shap to ..."
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented, using pseudo-code if relevant.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative Solutions
      description: >
        Please describe any alternative solution (existing functionality, 3rd party package, etc.)
        that would satisfy the feature request.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please provide any relevant GitHub issues, code examples or references that help describe and support
        the feature request.
