name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - "shap/**"
      - "tests/**"
      - "data/**"
      - ".github/workflows/run_tests.yml"
      - "pyproject.toml"
      - "setup.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel only PR intermediate builds
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

# Temporary simpler job for debugging purposes
jobs:
  run_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install eager pytest torch scikit-learn lightgbm
      - name: pip list
        run: pip list
      - name: Test with pytest
        run: >
          pytest tests/test_bug121101.py
